drupal:
  service:
    type: NodePort
    port: 80
    nodePort: 31080

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      interval: 15s
      additionalLabels: {}

  mariadb:
    enabled: true
    rootUser:
      password: drupal-root-password
    db:
      user: drupal
      password: drupal-password
      name: drupaldb

  persistence:
    enabled: true
    storageClass: local-path #ge√§ndert, da der Pod Probleme beim deployment hatte
    size: 8Gi
